---
development:
  cloud_name: bogotasegura
  api_key: ENV['CLOUDINARY_KEY']
  api_secret: ENV['CLOUDINARY_SECRET']
  enhance_image_tag: true
  static_image_support: false
  secure: true
production:
  cloud_name: bogotasegura
  api_key: ENV['CLOUDINARY_KEY']
  api_secret: ENV['CLOUDINARY_SECRET']
  enhance_image_tag: true
  static_image_support: false
  secure: true
test:
  cloud_name: bogotasegura
  api_key: ENV['CLOUDINARY_KEY']
  api_secret: ENV['CLOUDINARY_SECRET']
  enhance_image_tag: true
  static_image_support: false
  secure: true
